name: notionBizCard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - pip=25.0.1
  - blinker=1.9.0
  - certifi=2025.1.31
  - charset-normalizer=3.4.1
  - click=8.1.8
  - flask=3.1.0
  - idna=3.10
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - packaging=24.2
  - pillow=11.1.0
  - pytesseract=0.3.13
  - requests=2.32.3
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - paramiko